default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: assets
  cache_path: tmp/cache/webpacker
  resolved_paths: []
  cache_manifest: false

  extensions:
    - .jsx
    - .js
    - .scss
    - .css
    - .svg
    - .png
    - .jpg
    - .gif

development:
  <<: *default
  compile: true

  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: /node_modules/

test:
  <<: *default
  compile: true
  public_output_path: assets-test

production:
  <<: *default
  compile: false
  cache_manifest: true
